### ISSUE TITLE
Shortcut doesn't work

### ISSUE THREAD

**Issue by yunkai909** [markohlebar/Import#15]
I  have installed  successed，but  the shortcut  doesn't work。

**Comment by markohlebar** [comment]
Hi @BestKai do you see the menu item `Xcode -> Editor -> Import -> ☝️`? 
If so, check `Xcode -> Preferences -> Key Bindings` and check if that is set. 
If those are actually set, can you tell me how you are trying to use the extension?

**Comment by yunkai909** [comment]
it worked ,thank you very much.

发自我的 iPhone

**Comment by markohlebar** [comment]
@BestKai that's awesome, cheers!
