### ISSUE TITLE
[Feature Request] The ability to have `@class` work too

### ISSUE THREAD

**Issue by clementpadovani** [markohlebar/Import#17]
The ability of having Objective-C class/protocol forward declarations in ObjC headers would be great.

**Comment by markohlebar** [comment]
@ClementPadovani I was thinking about this for Peckham... I think we can't do anything that is automagic because you have no awareness if you are currently in the `.h` or `.m` file... 

Creating another action would probably work better, so that you can leave the decision of wether to do `#import` or `@class` to the user?

**Comment by clementpadovani** [comment]
Actually with XcodeKit we can, per [`XCSourceTextBuffer`](https://developer.apple.com/reference/xcodekit/xcsourcetextbuffer)’s [`contentUTI`](https://developer.apple.com/reference/xcodekit/xcsourcetextbuffer/2097266-contentuti) property I get an UTI of `public.c-header` for the headers and `public.objective-c-source` for Objective-C implementation files.

**Comment by markohlebar** [comment]
@ClementPadovani you are perfectly right :) but still sometimes a dev wants to explicitly add a header, so I think just forcing it to `@class` wouldn't really work, or do you have a better idea?

**Comment by clementpadovani** [comment]
Oh yeah, but my idea wasn't to replace #imports by forward declarations. It was just the possibility to add @class to the top like for importa

Thanks, Clément

**Comment by markohlebar** [comment]
Yeah, I didn't mean replacing them. When you add a new one, you should have a choice whether you want to add `@class` or `#import` right?

**Comment by clementpadovani** [comment]
Closed with #23
