### ISSUE TITLE
Error: When triggering the shortcut and moving the import to the top, also the editor scroll up now

### ISSUE THREAD

**Issue by ForestRingGames** [markohlebar/Import#22]
Since the latest Xcode version it seems like that the editor scroll all the way to the top when entering a new include which makes this plugin quite unusable since you can't keep your focus at the current line.

Is there a cure for this?

**Comment by markohlebar** [comment]
Hey @ForestRingGames, just tested this on `Xcode 8.3.2 (8E2002)`, and it works well for me. 
Can you tell me which version of Import you have installed when you look at `Applications -> Import`? 

@ClementPadovani can you confirm?

**Comment by clementpadovani** [comment]
@markohlebar Yes I can confirm everything work’s A-OK; however I do confirm that the scrolling to the top is annoying but it is due to #7. I did start working on a fix but haven’t had time to continue. Will try to check it out this weekend.

**Comment by markohlebar** [comment]
@ClementPadovani hmmm, it doesn't scroll to the top for me 🤔

**Comment by clementpadovani** [comment]
@markohlebar Actually yeah, it doesn’t really scroll all the way to the top, however the insertion point looses focus from our previous line.

**Comment by markohlebar** [comment]
@ClementPadovani oh yeah that's true, that needs to be fixed 👍.

**Comment by ForestRingGames** [comment]
Yes, I can confirm - sorry. It doesn't scroll all the way, just like 1-2 pages to the top. I tried it with a larger file now.

**Comment by clementpadovani** [comment]
Fixed w/ #24
