### ISSUE TITLE
something wrong

### ISSUE THREAD

**Issue by kevinYiLin** [markohlebar/Import#4]
import just support swift ?

**Comment by kevinYiLin** [comment]
i changed code sign both import and ImportExtension 
the app can build and run , but Editor -->   i can't find  'import'

**Comment by kevinYiLin** [comment]
finally i can see the menu 'import' , but it not work 

i check menu  -> System Preferences... -> Extensions -> All -> Enable Import , can't find 'enable import'

**Comment by markohlebar** [comment]
Hey @kevinYiLin, in your method, let's say 

```
- (void)someMethod {
#import "SomeImport.h" 
}
```

Press `cmd + ctrl + P` while in the `#import "SomeImport.h"` line and it should automatically put the import in the right place.
