### ISSUE TITLE
the cmd+ctrl+P doesn't work 

### ISSUE THREAD

**Issue by lizhaobomb** [markohlebar/Import#6]
the cmd+ctrl+P doesn't work

**Comment by markohlebar** [comment]
Hi @lizhaobomb, which system and Xcode version are you on and what did you try? 
Do you see the `Xcode -> Editor -> Import -> ☝️` menu? 
Also, if you go to `Xcode -> Preferences -> Key Bindings -> In Filter type "Import"` do you see any key binding set for it?

**Comment by lizhaobomb** [comment]
thanks @markohlebar ..now it works well, I haven't  set any key binding for it
